[package]
name = "caw_core_next"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
caw_builders = { version = "0.1", path = "../builders" }
cpal = "0.15"

[[example]]
name = "saw_print_values"

[[example]]
name = "saw_cpal"
