[package]
name = "currawong_interactive"
description = "Use mouse and keyboard to control currawong synhesizer"
version = "0.1.0"
edition = "2021"

[features]
default = ["midi"]
midi = ["currawong/midi"]

[dependencies]
anyhow = "1.0"
currawong = { version = "0.1", path = "../currawong" }
line_2d = "0.5"
rgb_int = "0.1"
sdl2 = "0.36"

[dev-dependencies]
clap = { version = "4.4", features = ["derive"] }
env_logger = "0.10"

[[example]]
name = "saw"

[[example]]
name = "drone"

[[example]]
name = "periodic_gate"

[[example]]
name = "keyboard_and_mouse"

[[example]]
name = "keyboard_and_mouse_monophonic"

[[example]]
name = "midi_file"

[[example]]
name = "midi_live"

[[example]]
name = "midi_live_with_serial"

[[example]]
name = "midi_live_with_serial_monophonic"

[[example]]
name = "car_sound"

[[example]]
name = "drum_machine"

[[example]]
name = "sample_playback"

[[example]]
name = "diy_square_wave"

[[example]]
name = "wub_wub"
