[package]
name = "ibis_interactive"
description = "Use mouse and keyboard to control ibis synhesizer"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = "0.35"
cpal = "0.15"

[[example]]
name = "hello"
