[package]
name = "ibis_interactive"
description = "Use mouse and keyboard to control ibis synhesizer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
cpal = "0.15"
log = "0.4"
sdl2 = "0.35"
rand = "0.8"
rgb_int = "0.1"
line_2d = "0.5"

[[example]]
name = "hello"
