[package]
name = "currawong_interactive"
version = "0.5.0"
edition = "2021"
description = "Interactive tools for currawong software-defined modular synthesizer"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
license = "MIT"
homepage = "https://github.com/gridbugs/currawong.git"
repository = "https://github.com/gridbugs/currawong.git"
documentation = "https://docs.rs/currawong_interactive"

[features]
default = ["midi"]
midi = ["currawong/midi"]

[dependencies]
anyhow = "1.0"
currawong = { version = "0.5", path = "../currawong" }
currawong_core = { version = "0.5", path = "../core" }
line_2d = "0.5"
rgb_int = "0.1"
sdl2 = "0.36"

[dev-dependencies]
clap = { version = "4.4", features = ["derive"] }
env_logger = "0.11"
rand = "0.8"

[[example]]
name = "saw"

[[example]]
name = "drone"

[[example]]
name = "periodic_gate"

[[example]]
name = "keyboard_and_mouse"

[[example]]
name = "keyboard_and_mouse_lofi"

[[example]]
name = "keyboard_and_mouse_monophonic"

[[example]]
name = "keyboard_and_mouse_chords"

[[example]]
name = "keyboard_and_mouse_arp"

[[example]]
name = "keyboard_and_mouse_arp_index_loops"

[[example]]
name = "keyboard_and_mouse_chords_arp"

[[example]]
name = "midi_file"

[[example]]
name = "midi_live"

[[example]]
name = "midi_live_with_serial"

[[example]]
name = "midi_live_with_serial_monophonic"

[[example]]
name = "drum_machine"

[[example]]
name = "wub_wub"

[[example]]
name = "drum_sequencer"

[[example]]
name = "basic_drum_sounds"

[[example]]
name = "random_notes"

[[example]]
name = "reverb_test"

[[example]]
name = "drum_reverb"

[[example]]
name = "pulse_wave_bass"
