[package]
name = "ibis_interactive"
description = "Use mouse and keyboard to control ibis synhesizer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
cpal = "0.15"
log = "0.4"
sdl2 = "0.35"
rand = "0.8"
rgb_int = "0.1"
line_2d = "0.5"
midly = "0.5"
midir = "0.9"

[dev-dependencies]
clap = { version = "4.4", features = ["derive"] }

[[example]]
name = "saw"

[[example]]
name = "drone"

[[example]]
name = "periodic_gate"

[[example]]
name = "keyboard_and_mouse"

[[example]]
name = "midi"
