[package]
name = "caw_computer_keyboard"
version = "0.1.0"
edition = "2021"

[dependencies]
caw_keyboard = { version = "0.1", path = "../keyboard" }
caw_core_next = { version = "0.1", path = "../core-next" }
