[package]
name = "caw_patches"
version = "0.1.0"
edition = "2021"

[dependencies]
caw_modules = { path = "../modules" }
caw_builder_proc_macros = { path = "../builder-proc-macros" }
caw_core = { path = "../core" }
