[package]
name = "caw_modules"
version = "0.1.0"
edition = "2021"

[dependencies]
caw_core_next = { path = "../core-next" }
caw_builder_proc_macros = { path = "../builder-proc-macros" }
itertools = "0.13"
wide = "0.7"
rand = "0.8"
log = "0.4"
