[workspace]

resolver = "2"

members = [
    "builder-proc-macros",
    "caw",
    "caw-next",
    "computer-keyboard",
    "core",
    "core-next",
    "interactive",
    "interactive-next",
    "keyboard",
    "modules",
]
