[workspace]

resolver = "2"

members = [
    "audio-file",
    "builder-proc-macros",
    "player",
    "computer-keyboard",
    "core",
    "interactive",
    "keyboard",
    "midi-file",
    "midi-live",
    "midi-serial",
    "midi",
    "modules",
    "patches",
    "utils",
]
