[package]
name = "caw"
version = "0.1.0"
edition = "2021"
description = "Combinatorial Audio Workstation: A software-defined modular synthesizer library"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
license = "MIT"
homepage = "https://github.com/gridbugs/caw.git"
repository = "https://github.com/gridbugs/caw.git"
documentation = "https://docs.rs/caw"

[features]
default = ["midi"]
midi = ["midly", "midir", "nix", "caw_core/midi"]
web = ["cpal/wasm-bindgen", "caw_core/web"]

[dependencies]
anyhow = "1.0"
cpal = "0.15"
caw_core = { version = "0.1", path = "../core", default-features = false }
log = "0.4"
midly = { version = "0.5", optional = true }
midir = { version = "0.9", optional = true }
nix = { version = "0.28", features = ["fs", "term"], optional = true }
hound = "3.5"

[[example]]
name = "periodic_gate_varying_period"

[[example]]
name = "car_sound_basic"

[[example]]
name = "lfo_pwm"

[[example]]
name = "tweet"

[[example]]
name = "drum_sounds"
