[package]
name = "caw_midi_file"
version = "0.1.0"
edition = "2021"

[dependencies]
midly = "0.5"
anyhow = "1"
caw_core = { version = "0.2", path = "../core" }
caw_midi = { version = "0.1", path = "../midi" }
