[package]
name = "caw_midi"
version = "0.1.0"
edition = "2021"

[dependencies]
midly = "0.5"
smallvec = "1.13"
caw_core = { version = "0.2", path = "../core" }
caw_keyboard = { version = "0.1", path = "../keyboard" }
