[package]
name = "currawong_core"
version = "0.2.0"
edition = "2021"
description = "Core types for currawong software-defined modular synthesizer"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
license = "MIT"
homepage = "https://github.com/gridbugs/currawong.git"
repository = "https://github.com/gridbugs/currawong.git"
documentation = "https://docs.rs/currawong_core"

[features]
default = ["midi"]
midi = ["midly"]

[dependencies]
rand = "0.8"
midly = { version = "0.5", optional = true }
