[package]
name = "caw_next"
version = "0.1.0"
edition = "2021"

[dependencies]
caw_core_next = { version = "0.1", path = "../core-next" }
caw_builders = { version = "0.1", path = "../builders" }

[[example]]
name = "saw"
