name: test
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable]
    steps:
    - if: matrix.os == 'ubuntu-latest'
      name: 'Install dependencies (ubuntu)'
      run: |
        sudo apt update
        sudo apt install libudev-dev libasound2-dev libsdl2-dev libsdl2-ttf-dev
    - name: Setup SDL2 frameworks
      uses: BrettDong/setup-sdl2-frameworks@main
      with:
        sdl2: latest
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - run: |
        cargo test --release
        cargo test --release --all-features
